export type WidgetType =
  | 'activeSelection'
  | 'XConnector'
  | 'XCircleNotes'
  | 'XFile'
  | 'XChart'
  | 'XFrame'
  | 'XMarkdown'
  | 'XGroup'
  | 'XImage'
  | 'XIText'
  | 'XObject'
  | 'XPath'
  | 'XPolyline'
  | 'XLine'
  | 'XRdRectPanel'
  | 'XRect'
  | 'XRectNotes'
  | 'XRectPanel'
  | 'XShape'
  | 'XShapeNotes'
  | 'XTriangle'
  | 'XURL'
  | 'XText'
  | 'XTextbox'
  | 'common'
  | 'XFileWord'
  | 'XFileExcel'
  | 'XFilePPT'
  | 'XFilePDF'
  | 'XFileZip'
  | 'XFileVideo'
  | 'XFileAudio';

 

export type WidgetFileType =
  | 'XFile'
  | 'XFileWord'
  | 'XFileExcel'
  | 'XFilePPT'
  | 'XFilePDF'
  | 'XFileZip'
  | 'XFileVideo'
  | 'XFileAudio';

