export enum FileEnum {
  DOC = 'doc',
  DOCX = 'docx',
  XLS = 'xls',
  XLSX = 'xlsx',
  PPT = 'ppt',
  PPTX = 'pptx',
  PDF = 'pdf',
  ZIP = 'zip',
  MP4 = 'mp4',
  WEBM = 'webm',

  MP3 = 'mp3',
  M4A = 'm4a',
  WAV = 'wav',
  AAC = 'aac',
  FLAC = 'flac',
  OGG = 'ogg',
  AIFF = 'aiff',
  WMA = 'wma',
  APE = 'ape',
  UNKNOWN = 'unknown',
}

export enum FileDocument {
  DOC = 'Word Document',
  DOCX = 'Word Document',
  XLS = 'Excel Document',
  XLSX = 'Excel Document',
  PPT = 'PPT Document',
  PPTX = 'PPT Document',
  PDF = 'PDF Document',
  ZIP = 'ZIP File',
  MP4 = 'Video Document',
  WEBM = 'Video Document',
  MP3 = 'Audio Document',
  M4A = 'Audio Document',
  WAV = 'Audio Document',
  AAC = 'Audio Document',
  FLAC = 'Audio Document',
  OGG = 'Audio Document',
  AIFF = 'Audio Document',
  WMA = 'Audio Document',
  APE = 'Audio Document',
}

export type FileType = keyof typeof FileEnum;
